services:
  frontend:
    container_name: frontend
    image: marketing-app-frontend
    build:
      context: ../../
      dockerfile: ./apps/frontend/Dockerfile
      target: frontend
    ports:
      - 80:80
