name: CI/CD

on:
  push:
    branches:
      - '**'

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install --ignore-scripts

      - name: Editorconfig
        run: pnpm editorconfig

      - name: Run linters
        run: pnpm lint

      - name: Run tests
        run: pnpm test

  deploy:
    runs-on: ubuntu-latest
    needs: test-and-lint
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Pull changes and stop containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd ${{ secrets.DO_PROJECT_PATH }}
            git pull origin main
            pnpm docker:down
            pnpm install --ignore-scripts

      - name: Build backend image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd ${{ secrets.DO_PROJECT_PATH }}
            pnpm api docker:build

      - name: Build frontend image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd ${{ secrets.DO_PROJECT_PATH }}
            pnpm web docker:build

      - name: Start containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd ${{ secrets.DO_PROJECT_PATH }}
            pnpm api docker:up
            pnpm api db:push
            pnpm web docker:up
